#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/home/nothecats/newest_de_10/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'encoder_bus_demo_0', class 'encoder_bus_demo'
 * The macros are prefixed with 'ENCODER_BUS_DEMO_0_'.
 * The prefix is the slave descriptor.
 */
#define ENCODER_BUS_DEMO_0_COMPONENT_TYPE encoder_bus_demo
#define ENCODER_BUS_DEMO_0_COMPONENT_NAME encoder_bus_demo_0
#define ENCODER_BUS_DEMO_0_BASE 0x0
#define ENCODER_BUS_DEMO_0_SPAN 1024
#define ENCODER_BUS_DEMO_0_END 0x3ff


#endif /* _ALTERA_HPS_0_H_ */
